import Head from 'next/head'
import Image from 'next/image'
import { VerticalSideBar } from '../components/Common/Sidebar/VerticalSideBar'
import { Layout } from '../Layout/Layout'
import styles from '../styles/Home.module.css'
import Dashboard from './dashboard'

export default function Home() {
  return (
    // <div className={styles.container}>
    <>
      <Head>
        <title>Prism</title>
        <meta name="description" content="Generated by Prism V2" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <>
        {/* <div id="preloader">
          <div id="status">
            <div className="spinner-chase">
              <div className="chase-dot"></div>
              <div className="chase-dot"></div>
              <div className="chase-dot"></div>
              <div className="chase-dot"></div>
              <div className="chase-dot"></div>
              <div className="chase-dot"></div>
            </div>
          </div>
        </div> */}
          <Dashboard/>
         
          {/* <div className="main-content">{this.props.children}</div> */}
      </>

    </>
  )
}
